language: python

jobs:
  include:
    - name: 'Classic'
      install:
        - export GAME_VERSION="classic"
        - export WOWHEAD_DOMAIN="classic"
    - name: 'TBC'
      install:
        - export GAME_VERSION="bcc"
        - export WOWHEAD_DOMAIN="tbc"

cache:
  directories:
    - /usr/local/lib/luarocks/rocks
  pip: true

addons:
  apt:
    packages:
      - luarocks

before_install:
  - sudo luarocks install luacheck
  - sudo luarocks install luaunit
  - sudo luarocks install luacov

before_script:
  - luacheck addon --no-color -q
  - luacheck tests --no-color -q
  - git clone https://github.com/Beast-Masters-addons/build_utils scripts/build_utils
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z -g $GAME_VERSION
  - mv .release/LibHunterPetInfo/libs .
  - pip install -r scripts/requirements.txt
  - python scripts/BuildPetData.py
  - python scripts/BuildMapData.py
  - python scripts/BuildLocale.py
  - python scripts/BuildFamilySpells.py
  - luacheck data --no-color -q --no-max-code-line-length

script:
  - cd tests
  - for test in test*.lua; do lua -lluacov "$test"; done

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cd $TRAVIS_BUILD_DIR
  - git add -f data/*.lua
  - git add -f locale/*.lua
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $GAME_VERSION

notifications:
  email:
    on_success: never
    on_failure: always
